name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -S . -B build -DTP_BUILD_EXAMPLES=OFF -DTP_BUILD_BENCHMARKS=OFF
        
      - name: configure clang
        run: cmake -S . -B build-clang -DTP_BUILD_EXAMPLES=OFF -DTP_BUILD_BENCHMARKS=OFF
        env:
          CC: clang
          CXX: clang++

      - name: build
        run: cmake --build build --config Debug -j4

      - name: build clang
        run: cmake --build build-clang --config Debug -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug

      - name: test clang
        run: |
          cd build-clang
          ctest --build-config Debug
